services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: unless-stopped
    environment:
      SA_PASSWORD: "123456@Abc"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - springnet

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - springnet

  app:
    build: .
    container_name: alotrabong
    restart: unless-stopped
    depends_on:
      - sqlserver
      - redis
    environment:
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://sqlserver:1433;databaseName=Alotrabong;encrypt=false"
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: "123456@Abc"
      EMBED_API_URL: "http://embed:8000/embed"
      QDRANT_API_URL: "http://qdrant:6333"
      GROQ_API_KEY: "sk-xxxx"
    ports:
      - "8080:8080"
    networks:
      - springnet

volumes:
  sqlserver_data:

networks:
  springnet:
