server:
  port: 8080

spring:
  application:
    name: alotrabong
  mvc:
    problemdetails:
      enabled: true
  
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=AloTraBong;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update

# springdoc:
#   api-docs:
#     enabled: true
#     path: /docs
#   swagger-ui:
#     enabled: true
#     path: /docs/ui

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

app:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:8080"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"